### ISSUE TITLE
Can not have Percy.Selenium and Percy.Appium in the same project?

### ISSUE THREAD

**Issue by jensakejohansson** [percy/percy-appium-dotnet#110]
Hi!

I've been using Percy.Selenium to take snapshot. Like this:

PercyIO.Selenium.Percy.Snapshot((WebDriver)Context.Driver, id, new Dictionary<string, object>
            {
                { "widths", widths},
                { "minHeight", minHeight }
            });

And in my .csproj I obviously have this:
PackageReference Include="PercyIO.Selenium" Version="2.0.0"

As soon as I add PercyIO.Appium to my project:
PackageReference Include="PercyIO.Appium" Version="3.0.1"

The previous code (the method shown above) stops working (I make no code changes at all).

Error: 
The type or namespace name 'Selenium' does not exist in the namespace 'PercyIO' (are you missing an assembly reference?)[CS0234]

Is there some sort of conflict between these to packages so they cannot co-exist in the same project? If so, it's a major drawback....

**Comment by itsjwala** [comment]
@prklm10 please update here with the details for the fix.

**Comment by prklm10** [comment]
@jensakejohansson, Sorry for late reply. We have fixed the issue in `v3.0.2` of this package.  cc: @itsjwala @ninadbstack

**Comment by jensakejohansson** [comment]
Thanks, now the project builds fine.
